-- Seed dummy storefront products for testing (idempotent by slug)

insert into public.products (
  slug, title, description, benefits, price, compare_at, stock, category, image, images,
  featured, bestseller, new_arrival, rating, reviews, tagline, taste_note,
  ingredients, how_to_use, highlights, faqs, weights, active
) values
-- Men's Care
(
  'mardana-taqat-majoon',
  'Mardana Taqat Majoon',
  'A classic Unani vitality majoon prepared for men''s stamina and everyday strength. Blended from warming herbs traditionally used to support energy, warmth, and resilience.',
  array['Supports daily stamina', 'Warming herbal blend', 'Traditional Unani formula', 'Ideal with warm milk'],
  1850, 2200, 48, 'mens-care',
  '/images/categories/mens-care.webp',
  array['/images/categories/mens-care.webp', '/images/hero-products.webp', '/images/categories/majoon.webp'],
  true, true, false, 4.8, 126,
  'Traditional men''s vitality majoon',
  'Warm, mildly sweet · Herbal resin note',
  array['Asgandh', 'Gond Singhara', 'Safed Musli', 'Honey base', 'Unani aromatic spices'],
  array['Take 5–10 g once or twice daily with warm milk.', 'Best after meals.', 'Store sealed in a cool, dry place.'],
  array['Clinic-trusted recipe', 'COD nationwide', 'Prepared in small batches'],
  '[{"q":"Who is this for?","a":"Adult men seeking traditional Unani support for stamina and warmth."},{"q":"Any side effects?","a":"Use as directed. If you have a medical condition, consult our clinic first."}]'::jsonb,
  '[{"value":50,"unit":"g","price":1100,"compare_at":1350},{"value":100,"unit":"g","price":1850,"compare_at":2200},{"value":200,"unit":"g","price":3400,"compare_at":4000}]'::jsonb,
  true
),
(
  'ashwagandha-mens-tonic',
  'Ashwagandha Men''s Tonic Powder',
  'Finely milled ashwagandha powder for men who want a clean, traditional adaptogenic tonic they can mix into warm milk or water.',
  array['Supports calm energy', 'Easy daily powder', 'Pure ground root', 'Pairs well with milk'],
  980, 1200, 60, 'mens-care',
  '/images/categories/mens-care.webp',
  array['/images/categories/mens-care.webp', '/images/categories/powders.webp'],
  false, true, true, 4.7, 89,
  'Pure ashwagandha for daily vitality',
  'Earthy, slightly bitter · Root powder',
  array['Ashwagandha root powder'],
  array['Mix ½–1 teaspoon in warm milk or water once daily.', 'Prefer evening use if winding down.', 'Keep dry and airtight.'],
  array['Single-ingredient purity', 'Milled fresh', 'No fillers'],
  '[{"q":"Is this sweetened?","a":"No. It is pure powder without sugar."}]'::jsonb,
  '[{"value":50,"unit":"g","price":580,"compare_at":700},{"value":100,"unit":"g","price":980,"compare_at":1200}]'::jsonb,
  true
),
(
  'roghan-mardana-oil',
  'Roghan Mardana Massage Oil',
  'A warming Unani massage oil traditionally used for men''s care routines. Light herbal aroma with a soothing finish.',
  array['Warming massage oil', 'Herbal Unani blend', 'Easy to apply', 'For external use'],
  1450, 1750, 35, 'mens-care',
  '/images/categories/oils.webp',
  array['/images/categories/oils.webp', '/images/categories/mens-care.webp'],
  false, false, true, 4.6, 54,
  'Warming herbal oil for men''s care',
  'Herbal, lightly aromatic · Oil',
  array['Sesame oil base', 'Unani warming herbs'],
  array['Warm a few drops between palms.', 'Massage gently as needed.', 'External use only.'],
  array['Traditional preparation', 'Smooth texture', 'Clinic favorite'],
  '[{"q":"Can it be used internally?","a":"No. This oil is for external massage only."}]'::jsonb,
  '[{"value":50,"unit":"g","price":850,"compare_at":1000},{"value":100,"unit":"g","price":1450,"compare_at":1750}]'::jsonb,
  true
),
-- Women's Care
(
  'safoof-banaspati-women',
  'Safoof Banaspati Women''s Care',
  'A gentle herbal powder crafted for women''s wellness routines. Traditionally used to support balance, comfort, and everyday vitality.',
  array['Women''s wellness blend', 'Gentle herbal powder', 'Easy to mix', 'Traditional Unani care'],
  1250, 1500, 42, 'womens-care',
  '/images/categories/womens-care.webp',
  array['/images/categories/womens-care.webp', '/images/categories/powders.webp', '/images/hero-products.webp'],
  true, true, false, 4.9, 142,
  'Herbal support for women''s balance',
  'Mild herbal · Soft powder',
  array['Shatavari', 'Ashwagandha', 'Selected Unani botanicals'],
  array['Take ½–1 teaspoon with warm water or milk after meals.', 'Use consistently for best routine support.', 'Consult clinic if pregnant or nursing.'],
  array['Women-focused formula', 'Smooth mixability', 'Clinic guided'],
  '[{"q":"Is this suitable during pregnancy?","a":"Please consult our clinic before use if pregnant or nursing."}]'::jsonb,
  '[{"value":50,"unit":"g","price":750,"compare_at":900},{"value":100,"unit":"g","price":1250,"compare_at":1500}]'::jsonb,
  true
),
(
  'gulnar-women-tonic',
  'Gulnar Women''s Herbal Tonic',
  'A classic botanical tonic inspired by Unani women''s care traditions, prepared for gentle daily support.',
  array['Daily wellness tonic', 'Botanical Unani blend', 'Mild taste profile', 'Trusted clinic recipe'],
  1600, 1900, 30, 'womens-care',
  '/images/categories/womens-care.webp',
  array['/images/categories/womens-care.webp', '/images/categories/majoon.webp'],
  false, false, true, 4.7, 67,
  'Gentle Unani tonic for women',
  'Mildly sweet · Floral herbal',
  array['Gulnar', 'Supporting Unani herbs', 'Natural base'],
  array['Take as advised, typically once daily after meals.', 'Store away from heat and moisture.'],
  array['Traditional botanicals', 'Small-batch made', 'Clear usage guidance'],
  '[{"q":"How long before I notice a difference?","a":"Herbal routines vary. Many customers use consistently for 2–4 weeks."}]'::jsonb,
  '[{"value":50,"unit":"g","price":950,"compare_at":1100},{"value":100,"unit":"g","price":1600,"compare_at":1900}]'::jsonb,
  true
),
(
  'women-hair-nourishing-oil',
  'Women''s Hair Nourishing Oil',
  'A nourishing hair oil blend for scalp comfort and shine, prepared with herbs commonly used in Pakistani homes.',
  array['Nourishes scalp & hair', 'Herbal fragrance', 'Weekly self-care ritual', 'External use'],
  1350, 1600, 55, 'womens-care',
  '/images/categories/oils.webp',
  array['/images/categories/oils.webp', '/images/categories/womens-care.webp'],
  false, true, false, 4.8, 118,
  'Herbal oil for shine and softness',
  'Floral herbal · Oil',
  array['Coconut/sesame oil base', 'Amla', 'Henna leaf extract notes', 'Aromatic herbs'],
  array['Warm lightly and massage into scalp.', 'Leave 30–60 minutes or overnight.', 'Wash with mild cleanser.'],
  array['Home-care favorite', 'Non-sticky feel', 'COD friendly packing'],
  '[{"q":"Suitable for all hair types?","a":"Yes for most hair types. Patch test if you have a sensitive scalp."}]'::jsonb,
  '[{"value":50,"unit":"g","price":800,"compare_at":950},{"value":100,"unit":"g","price":1350,"compare_at":1600},{"value":200,"unit":"g","price":2500,"compare_at":2950}]'::jsonb,
  true
),
-- Majoon
(
  'majoon-supari-pak',
  'Majoon Supari Pak',
  'A rich traditional majoon prepared with time-honored Unani ingredients. Dense, aromatic, and made for measured daily use.',
  array['Classic Unani majoon', 'Rich herbal paste', 'Measured spoonfuls', 'Long shelf life when sealed'],
  2100, 2500, 40, 'majoon',
  '/images/categories/majoon.webp',
  array['/images/categories/majoon.webp', '/images/hero-products.webp', '/images/100-natural.webp'],
  true, true, false, 4.9, 201,
  'Signature traditional majoon',
  'Sweet-herbal · Dense paste',
  array['Supari pak base herbs', 'Honey/sugar traditional base', 'Aromatic Unani spices'],
  array['Take a small spoonful (about 5–10 g) as advised.', 'Prefer after meals with warm water or milk.', 'Keep jar tightly closed.'],
  array['Clinic signature', 'Authentic texture', 'Generational recipe style'],
  '[{"q":"Is it very sweet?","a":"It has a traditional sweet-herbal profile typical of majoon."}]'::jsonb,
  '[{"value":50,"unit":"g","price":1250,"compare_at":1500},{"value":100,"unit":"g","price":2100,"compare_at":2500},{"value":200,"unit":"g","price":3900,"compare_at":4600}]'::jsonb,
  true
),
(
  'majoon-azaraqi',
  'Majoon Azaraqi',
  'A carefully prepared Unani majoon for customers seeking classical herbal support with authentic taste and texture.',
  array['Classical Unani formula', 'Small-batch preparation', 'Authentic majoon texture', 'Clinic recommended'],
  2400, 2850, 28, 'majoon',
  '/images/categories/majoon.webp',
  array['/images/categories/majoon.webp', '/images/categories/powders.webp'],
  false, false, true, 4.6, 45,
  'Classical Unani majoon preparation',
  'Bitter-sweet herbal · Dense',
  array['Azaraqi processed as per Unani practice', 'Supporting herbs', 'Traditional base'],
  array['Use only as directed by the practitioner.', 'Do not exceed recommended amount.', 'Keep away from children.'],
  array['Practitioner guided', 'Traditional processing', 'Limited batch'],
  '[{"q":"Can I self-dose freely?","a":"No. Follow the dosage guidance from our clinic."}]'::jsonb,
  '[{"value":50,"unit":"g","price":1400,"compare_at":1650},{"value":100,"unit":"g","price":2400,"compare_at":2850}]'::jsonb,
  true
),
(
  'majoon-jalinoos',
  'Majoon Jalinoos',
  'An aromatic Unani majoon inspired by classical texts, prepared for digestive comfort and general tonic use.',
  array['Digestive tonic majoon', 'Aromatic spice profile', 'Traditional Unani heritage', 'Measured use'],
  1750, 2100, 36, 'majoon',
  '/images/categories/majoon.webp',
  array['/images/categories/majoon.webp', '/images/categories/digestion.webp'],
  false, true, false, 4.7, 93,
  'Aromatic majoon for tonic support',
  'Spiced, warm · Herbal paste',
  array['Classical jalinoos herb mix', 'Warming spices', 'Traditional sweet base'],
  array['Take 5 g after meals unless advised otherwise.', 'Sip warm water afterward.', 'Seal jar after each use.'],
  array['Warm spice character', 'Everyday tonic style', 'Popular repeat order'],
  '[{"q":"Best time to take?","a":"Usually after meals. Follow your practitioner if advised differently."}]'::jsonb,
  '[{"value":50,"unit":"g","price":1050,"compare_at":1250},{"value":100,"unit":"g","price":1750,"compare_at":2100}]'::jsonb,
  true
),
-- Oils
(
  'roghan-badaam-shirin',
  'Roghan Badaam Shirin (Sweet Almond Oil)',
  'Pure sweet almond oil for hair, massage, and skin nourishment. A household staple with a light nutty character.',
  array['Nourishing almond oil', 'Hair & skin friendly', 'Light absorption', 'Multi-use bottle'],
  1200, 1450, 70, 'oils',
  '/images/categories/oils.webp',
  array['/images/categories/oils.webp', '/images/hero-products.webp'],
  true, true, false, 4.8, 176,
  'Everyday sweet almond oil',
  'Light nutty · Clean oil',
  array['Sweet almond oil'],
  array['Use a few drops for hair ends or gentle massage.', 'Can be warmed slightly before use.', 'External use.'],
  array['Single-origin feel', 'Clear bottle packing', 'Family essential'],
  '[{"q":"Is it edible?","a":"This listing is packed for topical / hair care use as sold in our store."}]'::jsonb,
  '[{"value":50,"unit":"g","price":700,"compare_at":850},{"value":100,"unit":"g","price":1200,"compare_at":1450},{"value":200,"unit":"g","price":2200,"compare_at":2600}]'::jsonb,
  true
),
(
  'roghan-surkh',
  'Roghan Surkh Relief Oil',
  'A warming red herbal oil traditionally used for massage on tired joints and muscles after long days.',
  array['Warming relief oil', 'Herbal Unani style', 'Massage friendly', 'External use only'],
  1550, 1850, 44, 'oils',
  '/images/categories/oils.webp',
  array['/images/categories/oils.webp', '/images/categories/mens-care.webp'],
  false, true, true, 4.7, 132,
  'Warming oil for muscle comfort',
  'Warm spice aroma · Oil',
  array['Sesame oil base', 'Warming Unani herbs', 'Natural colorants from herbs'],
  array['Massage onto clean skin as needed.', 'Wash hands after use.', 'Avoid eyes and broken skin.'],
  array['Deep warmth', 'Strong herbal scent', 'Clinic shelf staple'],
  '[{"q":"Can children use it?","a":"Use adult supervision and milder amounts. Ask the clinic for guidance."}]'::jsonb,
  '[{"value":50,"unit":"g","price":900,"compare_at":1100},{"value":100,"unit":"g","price":1550,"compare_at":1850}]'::jsonb,
  true
),
(
  'kalonji-hair-oil',
  'Kalonji Hair Oil',
  'Kalonji-infused hair oil for scalp care rituals. Earthy aroma and a traditional Pakistani self-care favorite.',
  array['Kalonji infused', 'Scalp care ritual', 'Earthy herbal scent', 'Weekly oiling'],
  1100, 1350, 58, 'oils',
  '/images/categories/oils.webp',
  array['/images/categories/oils.webp', '/images/categories/seeds.webp'],
  false, false, true, 4.6, 77,
  'Kalonji oil for traditional hair care',
  'Earthy, seeded · Oil',
  array['Base oil', 'Kalonji (nigella) infusion'],
  array['Massage into scalp 1–2 times weekly.', 'Leave at least 30 minutes before wash.', 'Store away from sunlight.'],
  array['Traditional infusion', 'Simple routine', 'Great with kalonji seeds'],
  '[{"q":"Does it stain?","a":"It may lightly tint light fabrics. Use a towel or old pillowcase."}]'::jsonb,
  '[{"value":50,"unit":"g","price":650,"compare_at":800},{"value":100,"unit":"g","price":1100,"compare_at":1350}]'::jsonb,
  true
),
-- Powders
(
  'triphala-powder',
  'Triphala Powder',
  'A balanced blend of three fruits used across classical herbal traditions for digestive wellness and gentle daily cleansing routines.',
  array['Classic digestive powder', 'Gentle daily blend', 'Easy to mix', 'Unsweetened'],
  850, 1050, 80, 'powders',
  '/images/categories/powders.webp',
  array['/images/categories/powders.webp', '/images/categories/digestion.webp'],
  true, true, false, 4.8, 164,
  'Everyday digestive herbal powder',
  'Tart-bitter · Fine powder',
  array['Amla', 'Harar', 'Bahera'],
  array['Mix ½–1 teaspoon in warm water at night or as advised.', 'Start with a smaller amount.', 'Keep moisture out of the jar.'],
  array['Three-fruit blend', 'Fine mill', 'Popular starter herb'],
  '[{"q":"Is it flavored?","a":"No added flavor. The taste is naturally tart-bitter."}]'::jsonb,
  '[{"value":50,"unit":"g","price":500,"compare_at":650},{"value":100,"unit":"g","price":850,"compare_at":1050},{"value":200,"unit":"g","price":1550,"compare_at":1900}]'::jsonb,
  true
),
(
  'haldi-powder-organic-style',
  'Haldi (Turmeric) Powder',
  'Bright turmeric powder for kitchen and wellness routines. Finely ground for smooth mixing in milk or recipes.',
  array['Kitchen & wellness use', 'Fine bright grind', 'Warm golden color', 'Everyday staple'],
  650, 800, 100, 'powders',
  '/images/categories/powders.webp',
  array['/images/categories/powders.webp', '/images/100-natural.webp'],
  false, true, false, 4.9, 220,
  'Golden turmeric for daily use',
  'Warm earthy · Fine powder',
  array['Turmeric rhizome powder'],
  array['Use in cooking or mix a pinch in warm milk.', 'Avoid staining fabrics and counters.', 'Seal after opening.'],
  array['Vibrant color', 'Fine texture', 'High-turnover favorite'],
  '[{"q":"Is this pure turmeric only?","a":"Yes, single-ingredient turmeric powder."}]'::jsonb,
  '[{"value":50,"unit":"g","price":380,"compare_at":450},{"value":100,"unit":"g","price":650,"compare_at":800},{"value":200,"unit":"g","price":1150,"compare_at":1400}]'::jsonb,
  true
),
(
  'multani-mitti-powder',
  'Multani Mitti Powder',
  'Classic multani mitti for facial and hair masks. Smooth clay powder for weekly self-care at home.',
  array['Clay mask powder', 'Hair & face masks', 'Absorbs oil', 'External beauty care'],
  450, 550, 90, 'powders',
  '/images/categories/powders.webp',
  array['/images/categories/powders.webp', '/images/categories/womens-care.webp'],
  false, false, true, 4.5, 61,
  'Smooth clay for home masks',
  'Earthy clay · Fine powder',
  array['Fuller''s earth (multani mitti)'],
  array['Mix with rose water or plain water to a paste.', 'Apply, let dry partially, then rinse.', 'External use only.'],
  array['Beauty aisle classic', 'Fine clay', 'Budget friendly'],
  '[{"q":"Can I use it daily?","a":"Most people use 1–2 times weekly depending on skin type."}]'::jsonb,
  '[{"value":100,"unit":"g","price":450,"compare_at":550},{"value":200,"unit":"g","price":800,"compare_at":950}]'::jsonb,
  true
),
-- Salajeet
(
  'salajeet-pure-resin',
  'Pure Salajeet Resin',
  'Mountain salajeet resin prepared for traditional use. Rich mineral character with authentic aroma and carefully packed portions.',
  array['Authentic resin form', 'Mineral-rich profile', 'Traditional use', 'Measured dosing'],
  2800, 3400, 25, 'salajeet',
  '/images/categories/salajeet.webp',
  array['/images/categories/salajeet.webp', '/images/hero-products.webp', '/images/100-natural.webp'],
  true, true, false, 4.9, 188,
  'Premium mountain salajeet resin',
  'Mineral, smoky · Soft resin',
  array['Purified salajeet resin'],
  array['Dissolve a rice-grain to pea-sized amount in warm water or milk.', 'Prefer morning use on an empty stomach unless advised otherwise.', 'Keep cool and sealed.'],
  array['Resin authenticity', 'Clinic recommended', 'High demand item'],
  '[{"q":"How do I know it is dissolving?","a":"Genuine salajeet softens and disperses in warm liquid."}]'::jsonb,
  '[{"value":10,"unit":"g","price":1600,"compare_at":1900},{"value":20,"unit":"g","price":2800,"compare_at":3400},{"value":50,"unit":"g","price":6200,"compare_at":7500}]'::jsonb,
  true
),
(
  'salajeet-capsules-style-powder',
  'Salajeet Powder',
  'Convenient salajeet powder for those who prefer scooping into warm drinks instead of handling resin.',
  array['Easy powder format', 'Warm drink friendly', 'Consistent scoops', 'Travel convenient'],
  2200, 2650, 32, 'salajeet',
  '/images/categories/salajeet.webp',
  array['/images/categories/salajeet.webp', '/images/categories/powders.webp'],
  false, true, true, 4.7, 97,
  'Salajeet in easy powder form',
  'Mineral earthy · Powder',
  array['Processed salajeet powder'],
  array['Mix a small scoop in warm water or milk once daily.', 'Do not exceed suggested amount.', 'Store dry.'],
  array['No sticky handling', 'Consistent portioning', 'Great starter format'],
  '[{"q":"Resin or powder - which is better?","a":"Both are traditional formats. Choose resin for classic use or powder for convenience."}]'::jsonb,
  '[{"value":20,"unit":"g","price":1400,"compare_at":1700},{"value":50,"unit":"g","price":2200,"compare_at":2650}]'::jsonb,
  true
),
(
  'salajeet-gold-blend',
  'Salajeet Gold Blend',
  'A premium salajeet blend prepared for customers who want a richer tonic experience with complementary herbs.',
  array['Premium blend', 'Tonic-style use', 'Gift-worthy packing', 'Limited stock feel'],
  3200, 3800, 18, 'salajeet',
  '/images/categories/salajeet.webp',
  array['/images/categories/salajeet.webp', '/images/categories/mens-care.webp'],
  true, false, true, 4.8, 52,
  'Premium salajeet tonic blend',
  'Deep mineral · Soft blend',
  array['Salajeet', 'Supporting tonic herbs'],
  array['Use as directed on the pack or by the clinic.', 'Start low and adjust only with guidance.'],
  array['Premium tier', 'Blend complexity', 'Popular gift'],
  '[{"q":"Is this pure salajeet only?","a":"It is a blend: salajeet with supporting tonic herbs."}]'::jsonb,
  '[{"value":20,"unit":"g","price":1900,"compare_at":2300},{"value":50,"unit":"g","price":3200,"compare_at":3800}]'::jsonb,
  true
),
-- Digestion
(
  'joshanda-digestive-herbs',
  'Joshanda Digestive Herbs',
  'A comforting herbal mix for seasonal wellness and digestive ease. Brew as a warm infusion when you need something soothing.',
  array['Warm herbal infusion', 'Seasonal comfort', 'Easy to brew', 'Family jar'],
  750, 950, 65, 'digestion',
  '/images/categories/digestion.webp',
  array['/images/categories/digestion.webp', '/images/categories/seeds.webp'],
  false, true, false, 4.7, 140,
  'Soothing brew for digestive comfort',
  'Spiced herbal · Loose mix',
  array['Selected Unani digestive herbs', 'Warming spices'],
  array['Steep 1 teaspoon in hot water for 5–8 minutes.', 'Strain and sip warm.', 'Use 1–2 times daily as needed.'],
  array['Home remedy classic', 'Aromatic steam', 'COD staple'],
  '[{"q":"Can I add honey?","a":"Yes, once slightly cooled you may add honey if desired."}]'::jsonb,
  '[{"value":50,"unit":"g","price":450,"compare_at":550},{"value":100,"unit":"g","price":750,"compare_at":950}]'::jsonb,
  true
),
(
  'pudina-digestive-powder',
  'Pudina Digestive Powder',
  'Refreshing mint-forward powder to support post-meal comfort. Light, aromatic, and easy to take after heavy meals.',
  array['Mint-forward comfort', 'After-meal friendly', 'Light aroma', 'Quick mix'],
  680, 850, 72, 'digestion',
  '/images/categories/digestion.webp',
  array['/images/categories/digestion.webp', '/images/categories/powders.webp'],
  false, false, true, 4.6, 58,
  'Minty powder for post-meal ease',
  'Cool mint · Fine powder',
  array['Pudina', 'Supporting digestive herbs'],
  array['Mix ½ teaspoon in warm water after meals.', 'Do not use boiling water on mint herbs if you want a fresher note.'],
  array['Refreshing profile', 'Travel pouch friendly', 'Everyday digestive'],
  '[{"q":"Is it spicy hot?","a":"No. It is minty and mild rather than chili-hot."}]'::jsonb,
  '[{"value":50,"unit":"g","price":400,"compare_at":500},{"value":100,"unit":"g","price":680,"compare_at":850}]'::jsonb,
  true
),
(
  'liver-care-herbal-mix',
  'Liver Care Herbal Mix',
  'A bitter-herbal mix traditionally used in Unani-inspired liver and digestive care routines. Best as a guided daily tonic.',
  array['Bitter tonic herbs', 'Digestive routine', 'Traditional profile', 'Clinic style blend'],
  1450, 1750, 38, 'digestion',
  '/images/categories/digestion.webp',
  array['/images/categories/digestion.webp', '/images/categories/majoon.webp'],
  true, false, false, 4.7, 84,
  'Herbal mix for liver & gut routines',
  'Bitter herbal · Coarse mix',
  array['Kasni', 'Supporting Unani liver herbs'],
  array['Prepare as an infusion or take powder form as labeled.', 'Prefer consistency over high doses.', 'Ask clinic for personalized advice.'],
  array['Bitter authenticity', 'Practitioner aligned', 'Steady seller'],
  '[{"q":"Does bitter mean spoiled?","a":"No. Bitterness is expected in many classical liver herbs."}]'::jsonb,
  '[{"value":50,"unit":"g","price":850,"compare_at":1000},{"value":100,"unit":"g","price":1450,"compare_at":1750}]'::jsonb,
  true
),
-- Seeds
(
  'kalonji-seeds',
  'Kalonji Seeds (Nigella)',
  'Cleaned kalonji seeds for kitchen, oil infusions, and traditional wellness routines. Aromatic and long-lasting when stored dry.',
  array['Whole kalonji seeds', 'Kitchen & wellness', 'Aromatic', 'Pantry staple'],
  550, 700, 110, 'seeds',
  '/images/categories/seeds.webp',
  array['/images/categories/seeds.webp', '/images/categories/oils.webp'],
  true, true, false, 4.8, 195,
  'Premium whole kalonji seeds',
  'Peppery, aromatic · Whole seed',
  array['Kalonji (nigella sativa) seeds'],
  array['Use in cooking, breads, or light roasting.', 'For oil infusion, follow a trusted method.', 'Keep airtight.'],
  array['Sorted & cleaned', 'Strong aroma', 'High repeat purchase'],
  '[{"q":"Should I grind them?","a":"You can use whole or freshly ground depending on the recipe."}]'::jsonb,
  '[{"value":100,"unit":"g","price":550,"compare_at":700},{"value":250,"unit":"g","price":1200,"compare_at":1500},{"value":500,"unit":"g","price":2200,"compare_at":2700}]'::jsonb,
  true
),
(
  'flax-seeds-alsi',
  'Flax Seeds (Alsi)',
  'Nutty flax seeds for smoothies, rotis, and soaked seed routines. A simple addition to everyday meals.',
  array['Omega-friendly seeds', 'Nutty taste', 'Soak or grind', 'Daily kitchen use'],
  480, 600, 95, 'seeds',
  '/images/categories/seeds.webp',
  array['/images/categories/seeds.webp', '/images/categories/powders.webp'],
  false, true, true, 4.6, 73,
  'Nutty alsi for everyday meals',
  'Mild nutty · Whole seed',
  array['Flax seeds (alsi)'],
  array['Soak overnight or grind fresh before use.', 'Add to yogurt, smoothies, or dough.', 'Refrigerate after grinding.'],
  array['Budget friendly', 'Versatile', 'Fresh grind recommended'],
  '[{"q":"Whole or powdered better?","a":"Whole stores longer; grind fresh when possible for best use."}]'::jsonb,
  '[{"value":100,"unit":"g","price":480,"compare_at":600},{"value":250,"unit":"g","price":1050,"compare_at":1300}]'::jsonb,
  true
),
(
  'tukhm-balanga',
  'Tukhm Balanga Seeds',
  'Traditional tukhm balanga seeds that swell into a gel when soaked. Popular in summer drinks and herbal kitchen culture.',
  array['Gel-forming seeds', 'Summer drink classic', 'Soaking ritual', 'Light neutral taste'],
  620, 780, 50, 'seeds',
  '/images/categories/seeds.webp',
  array['/images/categories/seeds.webp', '/images/categories/digestion.webp'],
  false, false, true, 4.5, 41,
  'Soaking seeds for traditional drinks',
  'Mild · Gel when soaked',
  array['Tukhm balanga seeds'],
  array['Soak 1 teaspoon in water until a gel forms.', 'Add to sherbets or drink as preferred.', 'Rinse seeds before soaking.'],
  array['Fun texture', 'Traditional summer use', 'Easy prep'],
  '[{"q":"Why do they become gel-like?","a":"The seed coat releases mucilage when soaked - that is expected."}]'::jsonb,
  '[{"value":50,"unit":"g","price":620,"compare_at":780},{"value":100,"unit":"g","price":1100,"compare_at":1350}]'::jsonb,
  true
)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  benefits = excluded.benefits,
  price = excluded.price,
  compare_at = excluded.compare_at,
  stock = excluded.stock,
  category = excluded.category,
  image = excluded.image,
  images = excluded.images,
  featured = excluded.featured,
  bestseller = excluded.bestseller,
  new_arrival = excluded.new_arrival,
  rating = excluded.rating,
  reviews = excluded.reviews,
  tagline = excluded.tagline,
  taste_note = excluded.taste_note,
  ingredients = excluded.ingredients,
  how_to_use = excluded.how_to_use,
  highlights = excluded.highlights,
  faqs = excluded.faqs,
  weights = excluded.weights,
  active = true,
  updated_at = now();
